#docker-compose web service should use the Dockerfile in the current directory

version: '3'
services:
  web:
    ports:
      - "3000:3000"
    build: .
    depends_on:
      - redis
  redis:
    image: "redis:alpine"