apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: koronet-test
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: koronet-test
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379